export enum EppStatus {
  DRAFT = 'DRAFT',
  REWORK = 'REWORK',
  REVIEW_MANAGER_EPP = 'REVIEW_MANAGER_EPP',
  REVIEW_MANAGER_PROGRAM = 'REVIEW_MANAGER_PROGRAM',
  REVIEW_SUPERVISOR = 'REVIEW_SUPERVISOR',
  REVIEW_MANAGER_FACULTY = 'REVIEW_MANAGER_FACULTY',
  READY_FOR_PUBLICATION = 'READY_FOR_PUBLICATION',
  CANCELLED = 'CANCELLED',
  WAITING = 'WAITING',
  DONE = 'DONE',
}
